version: "3"

services:

  api:
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api.camino.site
      LETSENCRYPT_HOST: api.camino.site
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: camino
    expose:
      - 4000
  
  postgres: 
    image: postgres:alpine
    expose:
      - 5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: nginx-proxy