version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
      - postgres
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api.camino.pw
      LETSENCRYPT_HOST: api.camino.pw
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: camino
    expose:
      - 4000
    command: npm install && npm run start
  
  postgres: 
    image: postgres:alpine
    expose:
      - 5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    command: createdb camino

networks:
  default:
    external:
      name: nginx-proxy