version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_PORT: ${NODE_PORT}
      PGHOST: postgres
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    command: npm run dev

  postgres: 
    image: postgres:alpine
    environment:
      PGUSER: ${PGUSER}
    expose:
      - ${PGPORT}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}