version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    ports:
      - 4000:4000
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: camino
    command: npm run dev

  postgres: 
    image: postgres:alpine
    volumes:
      - ./db/postgres:/var/lib/postgresql/data