version: "3"

services:

  api:
    build: .
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api.camino.site
      LETSENCRYPT_HOST: api.camino.site
      LETSENCRYPT_EMAIL: api.camino.site
    expose:
      - "80"
      - "443"

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - "27017"

networks:
  default:
    external:
      name: nginx-proxy