version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: camino
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: camino
    command: npm run dev

  mongo:
    image: mongo:jessie
    volumes:
      - ./db/mongo/db:/data/db

  postgres: 
    image: postgres:alpine
    volumes:
      - ./db/postgres:/var/lib/postgresql/data