version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.camino.local
      VIRTUAL_PORT: 4000
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: camino
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: camino
    expose:
      - 4000
    command: npm run dev

  mongo:
    image: mongo:jessie
    expose:
      - 27017
    volumes:
      - ./db/mongo/db:/data/db
  
  postgres: 
    image: postgres:alpine
    expose:
      - 5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: nginx-proxy