version: "3"

services:

  api:
    build: .
    depends_on: 
      - postgres
    environment:
      VIRTUAL_HOST: api.camino.pw
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: api.camino.pw
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: camino
      PGUSER: postgres
    expose:
      - 4000
  
  postgres: 
    image: postgres:alpine
    environment:
      PGUSER: postgres
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}

networks:
  default:
    external:
      name: nginx-proxy