version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    depends_on: 
      - postgres
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api.camino.pw
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: api.camino.pw
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: camino
      PGUSER: postgres
    expose:
      - 4000
    command: npm run start
  
  postgres: 
    image: postgres:alpine
    environment:
      PGUSER: postgres
    expose:
      - 5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    command: createdb camino

networks:
  default:
    external:
      name: nginx-proxy