version: "3"

services:

  api:
    build: .
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api.camino.site
      LETSENCRYPT_HOST: api.camino.site
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: camino
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: camino
    expose:
      - 4000

  mongo:
    image: mongo:jessie
    volumes:
      - ./data-mongo/db:/data/db
    expose:
      - 27017
  
  postgres: 
    image: postgres:alpine
    expose:
      - 5432
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: nginx-proxy