version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      DB_HOST: mongo
    command: npm run dev

  mongo:
    image: mongo:jessie
    volumes:
      - ./data/db:/data/db

  postgres: 
    image: postgres:alpine
    volumes:
      - ./data-postgres:/var/lib/postgresql/data