version: "3"

services:

  api:
    build: .
    volumes:
      - ./:/api
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.camino.local
    expose:
      - 80
      - 443
    command: npx nodemon app/index.js

  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db

networks:
  default:
    external:
      name: nginx-proxy