version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      NODE_PORT: 4000
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: camino
      PGUSER: postgres
    ports:
      - 4000:4000
    command: npm run dev

  postgres: 
    image: postgres:alpine
    environment:
      PGUSER: postgres
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}