version: "3"

services:

  api:
    image: node:alpine
    volumes:
      - ./:/api
    working_dir: /api
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.camino.local
      VIRTUAL_PORT: 3000
    expose:
      - 3000
    command: npm run dev

  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db

networks:
  default:
    external:
      name: nginx-proxy